apiVersion: v1
kind: Secret
metadata:
	name: {{ include "availabilitychecks.fullname" . }}-secrets
	labels:
{{ include "availabilitychecks.labels" . | nindent 4 }}
	{{- with .Values.azureAppConfig.annotations }}
	annotations:
{{ toYaml . | nindent 4 }}
	{{- end }}
type: Opaque
stringData:
  # Azure App Configuration
  azure-appconfig-connection-string: {{ .Values.azureAppConfig.azureAppConfigConnectionString | default "" | quote }}

  # Optional: only needed if you support Entra ID auth fallback
  azure-tenant-id: {{ .Values.azureAppConfig.azureTenantId | default "" | quote }}
  azure-client-id: {{ .Values.azureAppConfig.azureClientId | default "" | quote }}
  azure-client-secret: {{ .Values.azureAppConfig.azureClientSecret | default "" | quote }}